apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresfs-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/engage-rocket-dbfs/"
