apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresfs-pvc
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi