apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-spark-pv-volume
  labels:
    type: local
    app: jupyter-spark
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/jupyter-spark/"