apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-spark-pvc
  labels:
    type: local
    app: jupyter-spark
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi